version: '2'

services:
  web:
    image: nginx:latest
    container_name: "nginx-wordpress-example"
    ports:
      - "8823:80"
    env_file: .env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # - /var/log/iris:/var/log/nginx
      # - /u01/keys/iris/iris_ssl.crt:/etc/ssl/iris_ssl.crt
      # - /u01/keys/iris/iris_ssl.key:/etc/ssl/iris_ssl.key
    links:
      - php
    volumes_from:
      - app-data
  
  # logstash
  logstash:
    build: ./logstash
    container_name: "logstash-wordpress-example"

  # php
  php:  
    build: ./php/
    container_name: "php7-fpm-wordpress-example"
    env_file: .env
    # expose:
    #   - 9000
    links:
      - mysql
    volumes_from:
      - app-data

  # mysql
  mysql:
    image: mysql:5.7.21
    container_name: "mysql-wordpress"
    volumes_from:
      - mysql-data
    # ports:
    #  - "9306:3306"
    env_file: .env
  
  # wordpress data
  app-data:
    image: php:7.0-fpm
    container_name: "app-data-wordpress-example"
    volumes:
      - ./wordpress:/var/www/html
    command: "true"
  
  # mysql data
  mysql-data:
    image: mysql:5.7.21
    container_name: "mysql-data-wordpress"
    volumes:
      - ./db/mysql:/var/lib/mysql
    command: "true"
  
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-wordpress"
    ports:
      - 8824:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
